services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-backend
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/yourdbname
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    environment:
      - NODE_ENV=production
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  mongo-data: